# Generated by Django 4.1.7 on 2023-03-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciCommons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='articles', to='sciCommons.comment'),
        ),
    ]
