# Generated by Django 4.1.7 on 2023-03-22 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciCommons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeta',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to='sciCommons.article'),
        ),
        migrations.AddField(
            model_name='usermeta',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='sciCommons.article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(related_name='authors', to=settings.AUTH_USER_MODEL),
        ),
    ]
