# Generated by Django 4.1.7 on 2023-03-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciCommons', '0002_usermeta_bookmarks_usermeta_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='is_moderator',
        ),
    ]
