# Generated by Django 4.1.7 on 2023-03-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciCommons', '0003_article_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
