# Generated by Django 4.1.7 on 2023-03-22 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sciCommons', '0003_remove_membership_is_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeta',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='authors', to='sciCommons.article'),
        ),
        migrations.AddField(
            model_name='usermeta',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='sciCommons.comment'),
        ),
        migrations.AddField(
            model_name='usermeta',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to='sciCommons.article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
